### ISSUE TITLE
Messages not being processed (sometimes)

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#158]
Sometimes Commands not being pulled from the Queue, while NSB Host is running in Console and successfully "polling". and when restarted the NSB continues to process the messages.

![image](https://cloud.githubusercontent.com/assets/641348/3812549/5d34201e-1cab-11e4-8261-4a30d71f4c77.png)

![image](https://cloud.githubusercontent.com/assets/641348/3812507/09a3d674-1cab-11e4-9ce7-5672faf1bf58.png)

**Comment by SeanFeldman** [comment]
@yvesgoeleven @danielHalan is there any follow up on this?

**Comment by danielHalan** [comment]
We had a debug session regarding this, with a special Verbose build, and remember Yves noticing that the Handler was initiated (at least) once, which could be a possibility, and it is likely that there could be an exception / error occuring at that call (which is solved when restarting the service/internal state). But the question remains why no Error message is saved on the Message Header, and why it is not re-processed in a FLR/SLR fashion.

**Comment by yvesgoeleven** [comment]
It's because the processing is stuck/deadlocked no?, the message neither completes nor aborts, so FLR/SLR won't kick in and no other messages will be picked up either as the threads are just waiting... I remember that the handler was being invoked and then it got stuck somewhere. I'm currently assuming the deadlock is occuring somewhere inside the handler, have you ever been able to test that assumption?

**Comment by danielHalan** [comment]
Not sure if this was the case, as the Message is visible in the queue.

**Comment by yvesgoeleven** [comment]
ASB makes it visible again after the visible timeout elapses...

**Comment by danielHalan** [comment]
Ok, it was correct, after some further investigation found an infinity-loop inside NES
