### ISSUE TITLE
Add a azure queues/.net servicebus channels for the gateway 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Azure#22]
Raised by @andreasohlund
Migrated from by https://github.com/Particular/NServiceBus/issues/374

To improve our support for cloud <=> on-premise bridging we should add channels for both azure queues and .net servicebus to our gateway

**Comment by SimonCropp** [comment]
@yvesgoeleven assuming this is not required anymore.

**Comment by hfortegcmlp** [comment]
What was the reason to not implement this - we're actually still looking for a way to send from a msmq site directly to azure.

**Comment by yvesgoeleven** [comment]
@hfortegcmlp It's better to use the bridge pattern for your scenario, something similar to https://github.com/yvesgoeleven/NServiceBus.MsmqAsbBridge or https://github.com/yvesgoeleven/NServiceBus.AsbNativeIntegration. The gateway as it exists currently relies to much on http and the request reply pattern in order to allow swapping http for a broker based solution.

**Comment by hfortegcmlp** [comment]
@yvesgoeleven Thanks a lot - I'll take a look at that - definitely looks promising=)
