### ISSUE TITLE
Azure.Host performance issue

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#234]
Major performance difference between hosting as a Azure Worker and a regular NSB.Host, the perf. data is taken from a Worker(A2) and VM that is in the same Data Center and Affinity Group, with exact same configuration, except logging destination. The test case is a Saga that is sends out two commands and one event, that it-self processes, and then marks the SAGA complete when all are completed, and returns message to Originator. 
The result,

NSB.Host: ~0.6s
NSB.Azure.Host: 15-17s

From the logs its seems that the largest latency is when handling commands/events, as from Saga Start + Send Command, to the start process of the Commands it took ~9s (at which time both commands started processing simultaneously), and next major latency was between publishing and handling the event ~4s.

**Comment by danielHalan** [comment]
Sent a simple test project in the mail...

**Comment by yvesgoeleven** [comment]
Daniel,

Can you add following settings to your project? These settings must be made before any outbound connection is made from the process, otherwise the defaults would apply, constructor of the role entrypoint is probably the perfect spot.

      public WorkerRole()
      {
          ServicePointManager.DefaultConnectionLimit = 5000; // default settings only allows 2 concurrent requests per process to the same host
          ServicePointManager.UseNagleAlgorithm = false; // optimize for small requests
          ServicePointManager.Expect100Continue = false; // reduces number of http calls
          ServicePointManager.CheckCertificateRevocationList = false; // optional, only if you trust all your dependencies
      }

With these settings the total roundtrip time, for saga completion, should go down to around 0.9 - 1.1 seconds (at least it did for me) 

The reason is that the logging is also writing to storage, just like the saga and timeout infrastructure is, but by default only 2 concurrent requests to the same host address (azure storage is 1 dns host address) are allowed by the .net ServicePointManager, so your requests towards storage are just piling up and waiting. The other settings also help a bit to improve request performance, but not as significant as the number of allowed connections.
