### ISSUE TITLE
Diagnose why End2End tests are failing

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#319]
https://github.com/Particular/EndToEnd/pull/259

**Comment by SeanFeldman** [comment]
- Not happening in Debug, only Release
- Happens erratically 
- The issue is within ASB SDK. When `MessageReceiver.Close()` is called, it tries to abandon prefetched messages, but the internal `SbmpChannel` is closed, and then it tries to reconnect using `ChannelFactory`, but the factory is disposed as well. And that's when the `ObjectDisposedException` is thrown. This is happening in the ASB Client 4.x

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/22b23c422c32e389ade2aacfd837c3df611efc3a
